dist: trusty
sudo: false
language: python
python:
- '3.5'
install: pip install pelican beautifulsoup4
before_script:
- base64 -d <<< $DEPLOY_KEYS | tar -xz -C $HOME
script:
- make html
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: e6m+L9zCW9O8babmR995ZwlchiDYjqY9uOEK1nZvO2s0I9FoglnOd38KimfBmdTq4uIkfrPLyTO+c6WexL9e/EbkfCschlzcZjOUrbixHc0gU3xCtGlI54Mb96VyAeqCUw8FxcjVNYPTNmC5Dk3kM1a+t/nNMNBBS7mrzbVdaZgDHVI47cacKYV8dc8Y7WEtY/4HQrM0eN+r97G1zXIdWt0n/oDHz9isyAWq/ip9g13P3S8gscaqDWP+8jBisiDi9RuKG/00IHVI8LlRFhgl1+kP3iNYkMsvDbY3b0LEPYoxxCHr16+Uskx+6SSEPMpZn63W64nb9PBfvu2IrEZftt0GA7bZ1iQlR35UPCWT4tQ+v5Ro2PAoM0MZtgjzF+5SUX0X4LhsL4m0mfDQUPPbW7J1+/IYhG9lGs8k5744rYgRX1MOhCHyFzAsD+kltEWI6f9H2XQ4UXQDDApU8d5hFa9WkfUJwL4GamqDnuP0l/VUWrH8/VUhLgOlku8uY8gzyDtAlePBo5rBKmwGLPNUsleLrAlwmdGfjsJQASxbywcu57wMqBYh65iVWxIAMvKNY89jY5avGdo1tFcbrGQiBod7iKL01seMwS+lE1kJRsu1JW61df9kjclD2c/s1/cBEvGdfDH4eCfsy+6wbd8s484GLIWSN+ZVWbaRudpTYYE=
addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-lang-cyrillic
    - texlive-fonts-recommended
    - texlive-latex-extra
    - pgf
    - latex-beamer
after_success:
- make rsync_upload
